package com.souklemdina.app;

import static com.codename1.ui.CN.*;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Toolbar;
import com.souklemdina.entities.Panier;
import com.souklemdina.gui.AccueilSocial;
import com.souklemdina.gui.AfficherPanier;
import com.souklemdina.gui.GUILocal;
import com.souklemdina.gui.ListEvents;
import com.souklemdina.gui.ListeWorks;
import com.souklemdina.services.PanierServices;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose of building native mobile applications using Java.
 */
public class SoukLemdinaApp {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);
    }

    public void start() {
        if (current != null) {
            current.show();
            return;
        }
//        Form hi = new Form("Welcome", new BorderLayout(BorderLayout.CENTER_BEHAVIOR_CENTER_ABSOLUTE));
//        hi.show();
        AccueilSocial ac = new AccueilSocial();
        ac.getF().show();
        
//        ListeWorks ac = new ListeWorks();
//        ac.getf().show();
//        ListEvents le = new ListEvents();
//        le.getFe().show();
//        Panier p = new Panier(2, 3, "a.jpg", "tayara", "55", 2.);
//        PanierServices ps = new PanierServices();
//        ps.addPanier(p, 3);
//        AfficherPanier ap = new AfficherPanier();
    }

    public void stop() {
        current = getCurrentForm();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy() {
    }

}
